# Generated by Django 5.2.6 on 2025-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(
                choices=[
                    ('Africa/Abidjan', 'Africa/Abidjan'), ('Africa/Accra', 'Africa/Accra'),
                    ('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'),
                    ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'),
                    ('America/Toronto', 'America/Toronto'), ('America/Vancouver', 'America/Vancouver'),
                    ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'),
                    ('Europe/Berlin', 'Europe/Berlin'), ('Europe/Rome', 'Europe/Rome'),
                    ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Shanghai', 'Asia/Shanghai'),
                    ('Asia/Dubai', 'Asia/Dubai'), ('Australia/Sydney', 'Australia/Sydney'),
                    ('Pacific/Auckland', 'Pacific/Auckland'), ('UTC', 'UTC')
                ],
                default='UTC',
                help_text="User's preferred timezone for displaying dates and times",
                max_length=50
            ),
        ),
    ]
