# Generated by Django 5.2.6 on 2025-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_comment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='federated',
            field=models.BooleanField(default=False, help_text='If true, this post will be published to federation.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='activity_id',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
