# Generated by Django 5.2.6 on 2025-11-18 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_id", models.URLField(unique=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("Delete", "Delete"),
                            ("Follow", "Follow"),
                            ("Accept", "Accept"),
                            ("Reject", "Reject"),
                            ("Like", "Like"),
                            ("Undo", "Undo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("actor_uri", models.URLField()),
                ("object_uri", models.URLField(blank=True)),
                ("raw_activity", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("software", models.CharField(blank=True, max_length=50)),
                ("version", models.CharField(blank=True, max_length=20)),
                (
                    "trust_level",
                    models.IntegerField(
                        choices=[(0, "Blocked"), (1, "Limited"), (2, "Trusted")],
                        default=1,
                    ),
                ),
                ("shared_inbox", models.URLField(blank=True)),
                ("public_key", models.TextField(blank=True)),
                ("user_count", models.IntegerField(default=0)),
                ("post_count", models.IntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="RemoteUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_uri", models.URLField(unique=True)),
                ("username", models.CharField(max_length=50)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("inbox_url", models.URLField()),
                ("outbox_url", models.URLField(blank=True)),
                ("public_key", models.TextField()),
                ("last_fetched_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="federation.remoteinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("instance", "username")},
            },
        ),
    ]
