# Generated by Django 5.2.6 on 2025-11-24 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0002_add_activity_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_id', models.URLField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemotePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_id', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('in_reply_to', models.URLField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),

        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Follow', 'Follow'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Like', 'Like'), ('Undo', 'Undo'), ('Announce', 'Announce'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='remotefollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remotefollow',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_followers', to='federation.remoteuser'),
        ),
        migrations.AddField(
            model_name='remotepost',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='federation.remoteuser'),
        ),
        migrations.AlterUniqueTogether(
            name='remotefollow',
            unique_together={('follower', 'remote_user')},
        ),
        migrations.AddIndex(
            model_name='remotepost',
            index=models.Index(fields=['-published'], name='federation__publish_6f6c38_idx'),
        ),
    ]
